[project]
name = "epd-ble-sender"
version = "1.0.0"
description = "A command-line tool to send images and text to E-Paper Displays via BLE."
authors = [{ name = "Roo", email = "roo@example.com" }]
requires-python = ">=3.9"
dependencies = [
    "bleak",
    "click",
    "Pillow",
    "numpy",
]
